control_codes = {'NUL': 0,
                 'BS': 8,
                 'EOT': 4,
                 'CR': 13,
                 'SI': 15,
                 'DC3': 19,
                 'ESC': 27,
                 'SO': 14,
                 'FF': 12,
                 'DC1': 17,
                 'HT': 9,
                 'VT': 11,
                 'SUB': 26,
                 'BEL': 7,
                 'ETX': 3,
                 'CAN': 24,
                 'LF': 10,
                 'ENQ': 5}
